# 侧边栏主功能导航菜单
menubar:
  columns: 3 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    # - id: post # 页面中高亮的 menu_id
    #   theme: '#1BCDFC' # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
    #   icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
    #   title: 博客 # 标题
    #   url: / # 跳转链接，支持相对路径和绝对路径
    - id: Github
      theme: '#3DC550'
      icon: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
      title: Github
      url: https://github.com/fcbyoung
    - id: Bilibili
      theme: '#FA6400'
      icon: https://www.bilibili.com/favicon.ico
      title: B站
      url: https://space.bilibili.com/148884845
    - id: 网易云音乐
      theme: '#F44336'
      icon: https://music.163.com/favicon.ico
      title: 网易云音乐
      url: https://music.163.com/#/user/home?id=104779064	  